### PR TITLE
7 GitHub service

### PR DESCRIPTION
**Pull request by AAlvz**
Initial Commit. 
Create services for tinkerware

### CODE REVIEW

**Comment by AAlvz** [comment]
I created this new repo from a subfolder in infrastructure =) do you like it @thetonymaster ?

**Comment by thetonymaster** [comment]
I would :heart: if you used the convention for the branches more.

**Comment by thetonymaster** [comment]
So far it's good, let's try to keep our repos as smallest and meaningful as possible. :+1:

**Comment by AAlvz** [comment]
Convention? give me a link

**Comment by thetonymaster** [comment]
It it's not documented but, @iLeonelPerea and I use  {issue-number}-{feature/fix/bug/enhacement}/{name-of-the-branch}

**Comment by AAlvz** [comment]
my branch and that convention you're saying look practically the same :)

**Comment by thetonymaster** [comment]
This is kinda the convention [waffle faq](https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking) I guess I should let it pass anyway since it's an infrastructure repo, feature or another tag really makes no sense,  just as long it's tracked by waffle I guess it's ok. Keep up the good work.

**Comment by AAlvz** [comment]
I need your LGTM to merge it to master =)

**Comment by thetonymaster** [comment]
GO AHEAD AND FLY FREE LIKE THE WIND

image

**Comment by AAlvz** [comment]
Still can't see 'LGTM' =(

**Comment by thetonymaster** [comment]
Ok, LGTM.

**Comment by AAlvz** [comment]
Yaiii

**Pull request merged**
